var guanzhu="";
guanzhu += "<table width=\"372\" height=\"184\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" background=\"images/bg1.gif\">";
guanzhu += "  <tr>";
guanzhu += "    <td valign=\"top\"><table width=\"353\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">";
guanzhu += "      <tr>";
guanzhu += "        <td height=\"8\" colspan=\"2\"></td>";
guanzhu += "      </tr>";
guanzhu += "      <tr>";
guanzhu += "        <td height=\"20\" valign=\"bottom\" class=\"font14\">请选择您最关注的领域，最多不超过3项。</td>";
guanzhu += "        <td align=\"right\" valign=\"top\" class=\"font14\"><a href=\"#\" onclick=\"DialogHide()\"><img src=\"images/ico7.gif\" width=\"10\" height=\"10\" border=\"0\" /></a></td>";
guanzhu += "      </tr>";
guanzhu += "      <tr>";
guanzhu += "        <td height=\"4\" colspan=\"2\"></td>";
guanzhu += "      </tr>";
guanzhu += "      <tr>";
guanzhu += "        <td height=\"1\" colspan=\"2\" bgcolor=\"#DFDFDF\"></td>";
guanzhu += "      </tr>";
guanzhu += "      <tr>";
guanzhu += "        <td height=\"6\" colspan=\"2\"></td>";
guanzhu += "      </tr>";
guanzhu += "    </table>";
guanzhu += "      <table width=\"353\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">";
guanzhu += "        <tr>";
guanzhu += "          <td width=\"117\" height=\"26\"><input name=\"guanzhu\" id=\"guanzhu_0\" type=\"checkbox\"  value=\"管理软件\" />";
guanzhu += "          管理软件</td>";
guanzhu += "          <td width=\"117\"><input type=\"checkbox\" name=\"guanzhu\" id=\"guanzhu_1\" value=\"网络管理\" />";
guanzhu += "          网络管理</td>";
guanzhu += "          <td width=\"117\"><input type=\"checkbox\" name=\"guanzhu\" id=\"guanzhu_2\" value=\"服务器\" />";
guanzhu += "          服务器</td>";
guanzhu += "        </tr>";
guanzhu += "        <tr>";
 guanzhu += "         <td height=\"26\"><input type=\"checkbox\" name=\"guanzhu\" id=\"guanzhu_3\" value=\"项目管理\" />";
guanzhu += "          项目管理</td>";
guanzhu += "          <td><input type=\"checkbox\" name=\"guanzhu\" id=\"guanzhu_4\" value=\"操作系统\" />";
guanzhu += "          操作系统 </td>";
guanzhu += "          <td><input type=\"checkbox\" name=\"guanzhu\" id=\"guanzhu_5\" value=\"数据库\" />";
guanzhu += "          数据库</td>";
guanzhu += "        </tr>";
guanzhu += "        <tr>";
guanzhu += "          <td height=\"26\"><input type=\"checkbox\" name=\"guanzhu\" id=\"guanzhu_6\" value=\"信息安全\" />";
guanzhu += "          信息安全</td>";
guanzhu += "          <td><input type=\"checkbox\" name=\"guanzhu\" id=\"guanzhu_7\" value=\"开发/测试\" />";
guanzhu += "          开发/测试</td>";
guanzhu += "          <td><input type=\"checkbox\" name=\"guanzhu\" id=\"guanzhu_8\" value=\"存储\" />";
guanzhu += "          存储</td>";
guanzhu += "        </tr>";
guanzhu += "        <tr>";
guanzhu += "          <td height=\"26\"><input type=\"checkbox\" id=\"guanzhu_if_other\" onclick=\"disabletext('guanzhu',-1)\" name=\"guanzhu\" value=\"其它\" />";
guanzhu += "            <span class=\"font2\">";
 guanzhu += "           <input name=\"guanzhu_other\" id=\"guanzhu_other\" disabled=\"disabled\" type=\"text teat1_1\" class=\"teat6\"  value=\"其它..\" size=\"15\" maxlength='20'/>";
guanzhu += "          </span></td>";
guanzhu += "          <td>&nbsp;</td>";
guanzhu += "          <td>&nbsp;</td>";
guanzhu += "        </tr>";
guanzhu += "      </table>";
guanzhu += "      <table width=\"353\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">";
guanzhu += "        <tr>";
guanzhu += "          <td height=\"11\"></td>";
guanzhu += "        </tr>";
guanzhu += "        <tr>";
guanzhu += "          <td align=\"right\"><input type=image src=\"images/ico_queding.gif\" width=\"47\" height=\"22\" onclick=\"checkthisdiv('guanzhu',9,0)\"/> <a href=\"#\" onclick=\"DialogHide()\"><img src=\"images/ico_quxiao1.gif\" width=\"47\" height=\"22\" onclick=\"DialogHide()\"  border=0 /></a></td>";
guanzhu += "        </tr>";
guanzhu += "      </table></td>";
guanzhu += "  </tr>";
guanzhu += "</table>";