var hangye="";
hangye += "<table width=\"372\" height=\"184\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" background=\"../image/bbs/front/bg1.gif\">";
hangye += "  <tr>";
hangye += "    <td valign=\"top\"><table width=\"353\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">";
hangye += "      <tr>";
hangye += "        <td height=\"8\" colspan=\"2\"></td>";
hangye += "      </tr>";
hangye += "      <tr>";
hangye += "        <td height=\"20\" valign=\"bottom\" class=\"font14\">请选择您所属的行业，最多不超过3项。</td>";
hangye += "        <td align=\"right\" valign=\"top\" class=\"font14\"><a href=\"#\" onclick=\"DialogHide()\"><img src=\"../image/bbs/front/ico7.gif\" width=\"10\" height=\"10\" border=\"0\" /></a></td>";
hangye += "      </tr>";
hangye += "      <tr>";
hangye += "        <td height=\"4\" colspan=\"2\"></td>";
hangye += "      </tr>";
hangye += "      <tr>";
hangye += "        <td height=\"1\" colspan=\"2\" bgcolor=\"#DFDFDF\"></td>";
hangye += "      </tr>";
hangye += "      <tr>";
hangye += "        <td height=\"6\" colspan=\"2\"></td>";
hangye += "      </tr>";
hangye += "    </table>";
hangye += "      <table width=\"353\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">";
hangye += "        <tr>";
hangye += "          <td width=\"117\" height=\"26\"><input name=\"hangye\" id=\"hangye_0\"  type=\"checkbox\"   value=\"电信/通讯\" />";
hangye += "          电信/通讯</td>";
hangye += "          <td width=\"117\"><input type=\"checkbox\" name=\"hangye\" id=\"hangye_1\"  value=\"金融保险\" />";
hangye += "          金融保险</td>";
hangye += "          <td width=\"117\"><input type=\"checkbox\" name=\"hangye\" id=\"hangye_2\"  value=\"商贸流通\" />";
hangye += "          商贸流通</td>";
hangye += "        </tr>";
hangye += "        <tr>";
hangye += "          <td height=\"26\"><input type=\"checkbox\" name=\"hangye\" id=\"hangye_3\"  value=\"医药卫生\" />";
hangye += "          医药卫生</td>";
hangye += "          <td><input type=\"checkbox\" name=\"hangye\" id=\"hangye_4\"  value=\"能源化工\" />";
hangye += "          能源化工</td>";
hangye += "          <td><input type=\"checkbox\" name=\"hangye\" id=\"hangye_5\"  value=\"教育/科研\" />";
hangye += "          教育/科研</td>";
hangye += "        </tr>";
hangye += "        <tr>";
hangye += "          <td height=\"26\"><input type=\"checkbox\" name=\"hangye\" id=\"hangye_6\"  value=\"制造/加工\" />";
hangye += "          制造/加工</td>";
hangye += "          <td><input type=\"checkbox\" name=\"hangye\" id=\"hangye_7\"  value=\"政府部门\" />";
hangye += "          政府部门</td>";
hangye += "          <td><input type=\"checkbox\" name=\"hangye\" id=\"hangye_8\"  value=\"交通/运输\" />";
hangye += "          交通/运输</td>";
hangye += "        </tr>";
hangye += "        <tr>";
hangye += "          <td height=\"26\"><input type=\"checkbox\" name=\"hangye\" id=\"hangye_9\"  value=\"ISV / SI\" />";
hangye += "          ISV / SI</td>";
hangye += "          <td><input type=\"checkbox\" name=\"hangye\" id=\"hangye_10\"  value=\"互联网/信息技术\" />";
hangye += "          互联网/信息技术</td>";
hangye += "          <td><input type=\"checkbox\" name=\"hangye\" value=\"其它\" id=\"hangye_if_other\" onclick=\"disabletext('hangye',-1)\" />";
hangye += "            <span class=\"font2\">";
hangye += "            <input name=\"hangye_other\" id=\"hangye_other\" disabled=\"disabled\" type=\"text teat1_1\" class=\"teat6\" value=\"其它..\"  /> ";
hangye += "            </span></td>";
hangye += "        </tr>";
hangye += "      </table>";
hangye += "      <table width=\"353\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">";
hangye += "        <tr>";
hangye += "          <td height=\"11\"></td>";
hangye += "        </tr>";
hangye += "        <tr>";
hangye += "          <td align=\"right\"><input type=image src=\"../image/bbs/front/ico_queding.gif\" width=\"47\" height=\"22\" onclick=\"checkthisdiv('hangye',11,0)\"/> <a href=\"#\" onclick=\"DialogHide()\"><img src=\"../image/bbs/front/ico_quxiao1.gif\" width=\"47\" height=\"22\"  border=0 /></a></td>";
hangye += "        </tr>";
hangye += "      </table></td>";
hangye += "  </tr>";
hangye += "</table>";