var zhiwei = "";
zhiwei += "<table width=\"552\" height=\"524\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" background=\"images/bg3.gif\">";
zhiwei += "  <tr>";
zhiwei += "    <td valign=\"top\"><table width=\"534\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">";
zhiwei += "      <tr>";
zhiwei += "        <td height=\"8\" colspan=\"2\"></td>";
zhiwei += "      </tr>";
zhiwei += "      <tr>";
zhiwei += "        <td height=\"20\" valign=\"bottom\" class=\"font14\">具体职位：</td>";
zhiwei += "        <td align=\"right\" valign=\"top\" class=\"font14\"> <a href=\"#\" onclick=\"DialogHide()\"><img src=\"images/ico7.gif\" width=\"10\" height=\"10\" border=\"0\" /></a></td>";
zhiwei += "      </tr>";
zhiwei += "      <tr>";
zhiwei += "        <td height=\"4\" colspan=\"2\"></td>";
zhiwei += "      </tr>";
zhiwei += "      <tr>";
zhiwei += "        <td height=\"1\" colspan=\"2\" bgcolor=\"#DFDFDF\"></td>";
zhiwei += "      </tr>";
zhiwei += "      <tr>";
zhiwei += "        <td height=\"6\" colspan=\"2\"></td>";
zhiwei += "      </tr>";
zhiwei += "    </table>";
zhiwei += "      <table width=\"530\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">";
 zhiwei += "       <tr>";
zhiwei += "          <td width=\"132\" height=\"28\" valign=\"bottom\" class=\"font5\" style=\"font-weight:bold;\">IT管理</td>";
zhiwei += "          <td width=\"132\" valign=\"bottom\"><span class=\"font5\" style=\"font-weight:bold;\">IT技术</span></td>";
zhiwei += "          <td width=\"134\" valign=\"bottom\"><span class=\"font5\" style=\"font-weight:bold;\">非IT业务</span></td>";
zhiwei += "          <td width=\"132\" valign=\"bottom\"><span class=\"font5\" style=\"font-weight:bold;\">其他</span></td>";
zhiwei += "        </tr>";
zhiwei += "      </table>";
zhiwei += "      <table width=\"530\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">";
zhiwei += "        <tr>";
zhiwei += "          <td width=\"100\" height=\"26\"><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_0\" value=\"CIO/CTO\" />";
zhiwei += "          CIO/CTO</td>";
zhiwei += "          <td width=\"166\"><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_5\" value=\"系统架构师\" />";
zhiwei += "          系统架构师</td>";
zhiwei += "          <td width=\"139\"><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_21\" value=\"CEO/VP\" />";
zhiwei += "          CEO/VP</td>";
zhiwei += "          <td width=\"125\"><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_32\" value=\"学生\" />";
zhiwei += "学生</td>";
zhiwei += "        </tr>";
zhiwei += "        <tr>";
zhiwei += "          <td height=\"26\"><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_1\" value=\"技术总监\" />";
zhiwei += "          技术总监</td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_6\" value=\"分析师\" />";
zhiwei += "          分析师</td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_22\" value=\"财务主管\" />";
zhiwei += "          财务主管</td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_33\" value=\"技术爱好者\" />";
zhiwei += "技术爱好者</td>";
zhiwei += "        </tr>";
zhiwei += "        <tr>";
zhiwei += "          <td height=\"26\"><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_2\" value=\"技术经理\" />";
zhiwei += "          技术经理<br /></td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_7\"value=\"数据库开发工程师\" />";
zhiwei += "          数据库开发工程师<br /></td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_23\" value=\"产品主管/业务主管\" />";
zhiwei += "          产品主管/业务主管<br /></td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_34\" value=\"媒体人员\" />";
zhiwei += "媒体人员</td>";
zhiwei += "        </tr>";
zhiwei += "        <tr>";
zhiwei += "          <td height=\"26\"><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_3\" value=\"项目经理\" />";
zhiwei += "          项目经理<br /></td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_8\" value=\"数据库管理员\" />";
zhiwei += "          数据库管理员</td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_24\" value=\"生产管理/质量管理\" />";
zhiwei += "          生产管理/质量管理</td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_35\" value=\"公关/会展人员\" />";
zhiwei += "公关/会展人员</td>";
zhiwei += "        </tr>";
zhiwei += "        <tr>";
zhiwei += "          <td height=\"26\"><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_4\" value=\"IT顾问\" />";
zhiwei += "          IT顾问</td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_9\" value=\"软件工程师\" />";
zhiwei += "          软件工程师</td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_25\" value=\"销售/市场\" />";
zhiwei += "          销售/市场</td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_36\" value=\"行业协会工作者\" />";
zhiwei += "行业协会工作者</td>";
zhiwei += "        </tr>";
zhiwei += "        <tr>";
zhiwei += "          <td height=\"26\"><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_if_other_0\" value=\"其它\" onclick=\"disabletext('zhiwei',0)\" style=\"display:none\"/><input name=\"zhiwei_other_0\" id=\"zhiwei_other_0\" disabled=\"disabled\" class=\"te2\" value=\"其它..\" size=\"15\" style=\"display:none\"/></td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_10\" value=\"硬件工程师\" />";
zhiwei += "          硬件工程师</td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_26\" value=\"咨询/培训\" />";
zhiwei += "          咨询/培训</td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_if_other\" value=\"其它\" onclick=\"disabletext('zhiwei',-1)\" />";
zhiwei += "            <span class=\"font2\">";
zhiwei += "            <input name=\"zhiwei_other\" id=\"zhiwei_other\" disabled=\"disabled\"  type=\"text teat1_1\" class=\"teat6\" value=\"其它..\" size=\"15\" />";
zhiwei += "          </span></td>";
zhiwei += "        </tr>";
zhiwei += "        <tr>";
zhiwei += "          <td height=\"26\">&nbsp;</td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_11\" value=\"软件测试\" />";
zhiwei += "          软件测试</td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_27\" value=\"行政/人力资源\" />";
zhiwei += "          行政/人力资源<br /></td>";
zhiwei += "          <td>&nbsp;</td>";
zhiwei += "        </tr>";
zhiwei += "        <tr>";
zhiwei += "          <td height=\"26\">&nbsp;</td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_12\" value=\"硬件测试\" />";
zhiwei += "          硬件测试</td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_28\" value=\"客户服务\" />";
zhiwei += "          客户服务<br /></td>";
zhiwei += "          <td>&nbsp;</td>";
zhiwei += "        </tr>";
zhiwei += "        <tr>";
zhiwei += "          <td height=\"26\">&nbsp;</td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_13\" value=\"网站运营管理\" />";
zhiwei += "          网站运营管理</td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_29\" value=\"采购\" />";
zhiwei += "          采购</td>";
zhiwei += "          <td>&nbsp;</td>";
zhiwei += "        </tr>";
zhiwei += "        <tr>";
zhiwei += "          <td height=\"26\">&nbsp;</td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_14\" value=\"系统管理员\" />";
zhiwei += "          系统管理员</td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_30\" value=\"基建\" />";
zhiwei += "          基建</td>";
zhiwei += "          <td>&nbsp;</td>";
zhiwei += "        </tr>";
zhiwei += "        <tr>";
zhiwei += "          <td height=\"26\">&nbsp;</td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_15\" value=\"网络管理员\" />";
zhiwei += "          网络管理员</td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_31\" value=\"库管/物流\" />";
zhiwei += "          库管/物流</td>";
zhiwei += "          <td>&nbsp;</td>";
zhiwei += "        </tr>";
zhiwei += "        <tr>";
zhiwei += "          <td height=\"26\">&nbsp;</td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_16\" value=\"互联网软件开发工程师\" />";
zhiwei += "         互联网软件开发工程师</td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_if_other_2\" value=\"其它\" onclick=\"disabletext('zhiwei',2)\"  style=\"display:none\" /><input name=\"zhiwei_other_2\" id=\"zhiwei_other_2\" disabled=\"disabled\" class=\"te2\" value=\"其它..\" size=\"15\"  style=\"display:none\" /></td>";
zhiwei += "          <td>&nbsp;</td>";
zhiwei += "        </tr>";
zhiwei += "        <tr>";
zhiwei += "          <td height=\"26\">&nbsp;</td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_17\" value=\"网络工程师\" />";
zhiwei += "          网络工程师</td>";
zhiwei += "          <td>&nbsp;</td>";
zhiwei += "          <td>&nbsp;</td>";
zhiwei += "        </tr>";
zhiwei += "        <tr>";
zhiwei += "          <td height=\"26\">&nbsp;</td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_18\" value=\"网络与信息安全工程师\" />";
zhiwei += "          网络与信息安全工程师</td>";
zhiwei += "          <td>&nbsp;</td>";
zhiwei += "          <td>&nbsp;</td>";
zhiwei += "        </tr>";
zhiwei += "        <tr>";
zhiwei += "          <td height=\"26\">&nbsp;</td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_19\" value=\"程序员/开发者\" />";
zhiwei += "          程序员/开发者<br /></td>";
zhiwei += "          <td>&nbsp;</td>";
zhiwei += "          <td>&nbsp;</td>";
zhiwei += "        </tr>";
zhiwei += "        <tr>";
 zhiwei += "         <td height=\"26\">&nbsp;</td>";
 zhiwei += "         <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_20\" value=\"技术支持\" />";
zhiwei += "          技术支持<br /></td>";
zhiwei += "          <td><input type=\"checkbox\" name=\"zhiwei\" id=\"zhiwei_if_other_1\" value=\"其它\" onclick=\"disabletext('zhiwei',1)\" style=\"display:none\"/><input name=\"zhiwei_other_1\" id=\"zhiwei_other_1\" disabled=\"disabled\" class=\"te2\" value=\"其它..\" size=\"15\" style=\"display:none\" /></td>";
zhiwei += "          <td>&nbsp;</td>";
zhiwei += "        </tr>";
zhiwei += "      </table>";
zhiwei += "      <table width=\"520\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">";
zhiwei += "        <tr>";
zhiwei += "          <td height=\"10\"></td>";
zhiwei += "        </tr>";
zhiwei += "        <tr>";
zhiwei += "          <td align=\"right\"><input type=image src=\"images/ico_queding.gif\" width=\"47\" height=\"22\" onclick=\"checkthisdiv('zhiwei',37,0)\"/>  <a href=\"#\" onclick=\"DialogHide()\"><img src=\"images/ico_quxiao1.gif\" width=\"47\" height=\"22\" /></a></td>";
zhiwei += "        </tr>";
zhiwei += "      </table></td>";
zhiwei += "  </tr>";
zhiwei += "</table>";