var zhiye = "";
zhiye += "<table width=\"552\" height=\"524\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" background=\"../image/bbs/front/bg3.gif\">";
zhiye += "  <tr>";
zhiye += "    <td valign=\"top\"><table width=\"534\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">";
zhiye += "      <tr>";
zhiye += "        <td height=\"8\" colspan=\"2\"></td>";
zhiye += "      </tr>";
zhiye += "      <tr>";
zhiye += "        <td height=\"20\" valign=\"bottom\" class=\"font14\">具体职业：</td>";
zhiye += "        <td align=\"right\" valign=\"top\" class=\"font14\"> <a href=\"#\" onclick=\"DialogHide()\"><img src=\"../image/bbs/front/ico7.gif\" width=\"10\" height=\"10\" border=\"0\" /></a></td>";
zhiye += "      </tr>";
zhiye += "      <tr>";
zhiye += "        <td height=\"4\" colspan=\"2\"></td>";
zhiye += "      </tr>";
zhiye += "      <tr>";
zhiye += "        <td height=\"1\" colspan=\"2\" bgcolor=\"#DFDFDF\"></td>";
zhiye += "      </tr>";
zhiye += "      <tr>";
zhiye += "        <td height=\"6\" colspan=\"2\"></td>";
zhiye += "      </tr>";
zhiye += "    </table>";
zhiye += "      <table width=\"530\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">";
 zhiye += "       <tr>";
zhiye += "          <td width=\"132\" height=\"28\" valign=\"bottom\" class=\"font5\" style=\"font-weight:bold;\">IT管理</td>";
zhiye += "          <td width=\"132\" valign=\"bottom\"><span class=\"font5\" style=\"font-weight:bold;\">IT技术</span></td>";
zhiye += "          <td width=\"134\" valign=\"bottom\"><span class=\"font5\" style=\"font-weight:bold;\">非IT业务</span></td>";
zhiye += "          <td width=\"132\" valign=\"bottom\"><span class=\"font5\" style=\"font-weight:bold;\">其他</span></td>";
zhiye += "        </tr>";
zhiye += "      </table>";
zhiye += "      <table width=\"530\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">";
zhiye += "        <tr>";
zhiye += "          <td width=\"100\" height=\"26\"><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_0\" value=\"CIO/CTO\" />";
zhiye += "          CIO/CTO</td>";
zhiye += "          <td width=\"166\"><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_5\" value=\"系统架构师\" />";
zhiye += "          系统架构师</td>";
zhiye += "          <td width=\"139\"><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_21\" value=\"CEO/VP\" />";
zhiye += "          CEO/VP</td>";
zhiye += "          <td width=\"125\"><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_32\" value=\"学生\" />";
zhiye += "学生</td>";
zhiye += "        </tr>";
zhiye += "        <tr>";
zhiye += "          <td height=\"26\"><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_1\" value=\"技术总监\" />";
zhiye += "          技术总监</td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_6\" value=\"分析师\" />";
zhiye += "          分析师</td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_22\" value=\"财务主管\" />";
zhiye += "          财务主管</td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_33\" value=\"技术爱好者\" />";
zhiye += "技术爱好者</td>";
zhiye += "        </tr>";
zhiye += "        <tr>";
zhiye += "          <td height=\"26\"><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_2\" value=\"技术经理\" />";
zhiye += "          技术经理<br /></td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_7\"value=\"数据库开发工程师\" />";
zhiye += "          数据库开发工程师<br /></td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_23\" value=\"产品主管/业务主管\" />";
zhiye += "          产品主管/业务主管<br /></td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_34\" value=\"媒体人员\" />";
zhiye += "媒体人员</td>";
zhiye += "        </tr>";
zhiye += "        <tr>";
zhiye += "          <td height=\"26\"><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_3\" value=\"项目经理\" />";
zhiye += "          项目经理<br /></td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_8\" value=\"数据库管理员\" />";
zhiye += "          数据库管理员</td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_24\" value=\"生产管理/质量管理\" />";
zhiye += "          生产管理/质量管理</td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_35\" value=\"公关/会展人员\" />";
zhiye += "公关/会展人员</td>";
zhiye += "        </tr>";
zhiye += "        <tr>";
zhiye += "          <td height=\"26\"><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_4\" value=\"IT顾问\" />";
zhiye += "          IT顾问</td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_9\" value=\"软件工程师\" />";
zhiye += "          软件工程师</td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_25\" value=\"销售/市场\" />";
zhiye += "          销售/市场</td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_36\" value=\"行业协会工作者\" />";
zhiye += "行业协会工作者</td>";
zhiye += "        </tr>";
zhiye += "        <tr>";
zhiye += "          <td height=\"26\"><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_if_other_0\" value=\"其它\" onclick=\"disabletext('zhiye',0)\" style=\"display:none\"/><input name=\"zhiye_other_0\" id=\"zhiye_other_0\" disabled=\"disabled\" class=\"te2\" value=\"其它..\" size=\"15\" style=\"display:none\"/></td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_10\" value=\"硬件工程师\" />";
zhiye += "          硬件工程师</td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_26\" value=\"咨询/培训\" />";
zhiye += "          咨询/培训</td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_if_other\" value=\"其它\" onclick=\"disabletext('zhiye',-1)\" />";
zhiye += "            <span class=\"font2\">";
zhiye += "            <input name=\"zhiye_other\" id=\"zhiye_other\" disabled=\"disabled\"  type=\"text teat1_1\" class=\"teat6\" value=\"其它..\" size=\"15\" />";
zhiye += "          </span></td>";
zhiye += "        </tr>";
zhiye += "        <tr>";
zhiye += "          <td height=\"26\">&nbsp;</td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_11\" value=\"软件测试\" />";
zhiye += "          软件测试</td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_27\" value=\"行政/人力资源\" />";
zhiye += "          行政/人力资源<br /></td>";
zhiye += "          <td>&nbsp;</td>";
zhiye += "        </tr>";
zhiye += "        <tr>";
zhiye += "          <td height=\"26\">&nbsp;</td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_12\" value=\"硬件测试\" />";
zhiye += "          硬件测试</td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_28\" value=\"客户服务\" />";
zhiye += "          客户服务<br /></td>";
zhiye += "          <td>&nbsp;</td>";
zhiye += "        </tr>";
zhiye += "        <tr>";
zhiye += "          <td height=\"26\">&nbsp;</td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_13\" value=\"网站运营管理\" />";
zhiye += "          网站运营管理</td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_29\" value=\"采购\" />";
zhiye += "          采购</td>";
zhiye += "          <td>&nbsp;</td>";
zhiye += "        </tr>";
zhiye += "        <tr>";
zhiye += "          <td height=\"26\">&nbsp;</td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_14\" value=\"系统管理员\" />";
zhiye += "          系统管理员</td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_30\" value=\"基建\" />";
zhiye += "          基建</td>";
zhiye += "          <td>&nbsp;</td>";
zhiye += "        </tr>";
zhiye += "        <tr>";
zhiye += "          <td height=\"26\">&nbsp;</td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_15\" value=\"网络管理员\" />";
zhiye += "          网络管理员</td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_31\" value=\"库管/物流\" />";
zhiye += "          库管/物流</td>";
zhiye += "          <td>&nbsp;</td>";
zhiye += "        </tr>";
zhiye += "        <tr>";
zhiye += "          <td height=\"26\">&nbsp;</td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_16\" value=\"互联网软件开发工程师\" />";
zhiye += "         互联网软件开发工程师</td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_if_other_2\" value=\"其它\" onclick=\"disabletext('zhiye',2)\"  style=\"display:none\" /><input name=\"zhiye_other_2\" id=\"zhiye_other_2\" disabled=\"disabled\" class=\"te2\" value=\"其它..\" size=\"15\"  style=\"display:none\" /></td>";
zhiye += "          <td>&nbsp;</td>";
zhiye += "        </tr>";
zhiye += "        <tr>";
zhiye += "          <td height=\"26\">&nbsp;</td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_17\" value=\"网络工程师\" />";
zhiye += "          网络工程师</td>";
zhiye += "          <td>&nbsp;</td>";
zhiye += "          <td>&nbsp;</td>";
zhiye += "        </tr>";
zhiye += "        <tr>";
zhiye += "          <td height=\"26\">&nbsp;</td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_18\" value=\"网络与信息安全工程师\" />";
zhiye += "          网络与信息安全工程师</td>";
zhiye += "          <td>&nbsp;</td>";
zhiye += "          <td>&nbsp;</td>";
zhiye += "        </tr>";
zhiye += "        <tr>";
zhiye += "          <td height=\"26\">&nbsp;</td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_19\" value=\"程序员/开发者\" />";
zhiye += "          程序员/开发者<br /></td>";
zhiye += "          <td>&nbsp;</td>";
zhiye += "          <td>&nbsp;</td>";
zhiye += "        </tr>";
zhiye += "        <tr>";
 zhiye += "         <td height=\"26\">&nbsp;</td>";
 zhiye += "         <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_20\" value=\"技术支持\" />";
zhiye += "          技术支持<br /></td>";
zhiye += "          <td><input type=\"checkbox\" name=\"zhiye\" id=\"zhiye_if_other_1\" value=\"其它\" onclick=\"disabletext('zhiye',1)\" style=\"display:none\"/><input name=\"zhiye_other_1\" id=\"zhiye_other_1\" disabled=\"disabled\" class=\"te2\" value=\"其它..\" size=\"15\" style=\"display:none\" /></td>";
zhiye += "          <td>&nbsp;</td>";
zhiye += "        </tr>";
zhiye += "      </table>";
zhiye += "      <table width=\"520\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">";
zhiye += "        <tr>";
zhiye += "          <td height=\"10\"></td>";
zhiye += "        </tr>";
zhiye += "        <tr>";
zhiye += "          <td align=\"right\"><input type=image src=\"../image/bbs/front/ico_queding.gif\" width=\"47\" height=\"22\" onclick=\"checkthisdiv('zhiye',37,0)\"/>  <a href=\"#\" onclick=\"DialogHide()\"><img src=\"../image/bbs/front/ico_quxiao1.gif\" width=\"47\" height=\"22\" /></a></td>";
zhiye += "        </tr>";
zhiye += "      </table></td>";
zhiye += "  </tr>";
zhiye += "</table>";